/**
 * AUTO-GENERATED BITWIDTH CONFIGURATION FOR INT8 GRAPHSAGE HLS
 * 
 * Generated by: src/optimize_bitwidths_int8.py
 * Method: data-driven (validated against theoretical)
 * Safety margin: 2 bits
 * 
 * DO NOT EDIT MANUALLY - regenerate using the optimization script.
 * 
 * To regenerate:
 *   cd src
 *   python optimize_bitwidths_int8.py --safety-margin 2 --method both
 */

#ifndef AUTO_GENERATED_BITWIDTHS_H
#define AUTO_GENERATED_BITWIDTHS_H

// ============================================================================
// Model Architecture (extracted from PTQ model)
// ============================================================================

#define OPT_NUM_NODES       8
#define OPT_IN_FEATURES     16
#define OPT_HIDDEN_FEATURES 16
#define OPT_OUT_FEATURES    7

// ============================================================================
// Fixed-Point Configuration
// ============================================================================

// Fractional bits for scale factors
#define OPT_M_BITS 24

// Adjacency matrix scale: A_float * 2^K_BITS -> adj_t
#define OPT_K_BITS 12

// ============================================================================
// Optimized Bit-Widths
// ============================================================================

// Adjacency matrix entries (scaled integers)
// Theoretical max: 2^12 = 4096
// Actual max: 4096
#define OPT_ADJ_BITS 16

// Accumulator for MAC operations (aggregation and linear)
// Theoretical max: 2080768
// Actual max: 520192
#define OPT_ACC_BITS 22

// Fixed-point scale factors (eff_scale_fp, beta_fp)
// Max scale value: 235848
#define OPT_SCALE_BITS 21

// Intermediate product (acc * scale)
#define OPT_MULT_BITS 43

// ============================================================================
// Graph Statistics (for reference)
// ============================================================================

#define OPT_DEG_MAX 4  // Maximum node degree

// ============================================================================
// Fixed-Point Scale Values (for testbench reference)
// ============================================================================

#define OPT_EFF_SCALE1_FP 235848
#define OPT_EFF_SCALE2_FP 221043
#define OPT_BETA1_FP      254
#define OPT_BETA2_FP      4096

// ============================================================================
// Analysis Report
// ============================================================================

/*
 * Theoretical Analysis (worst-case bounds):
 *   ADJ_BITS:   15
 *   ACC_BITS:   24
 *   SCALE_BITS: 32
 *   MULT_BITS:  56
 *
 * Data-Driven Analysis (actual simulation):
 *   ADJ_BITS:   16
 *   ACC_BITS:   22
 *   SCALE_BITS: 21
 *   MULT_BITS:  43
 *
 * Savings vs defaults (32-bit acc, 64-bit mult):
 *   ADJ:   0 bits saved
 *   ACC:   10 bits saved
 *   SCALE: 11 bits saved
 *   MULT:  21 bits saved
 */

#endif // AUTO_GENERATED_BITWIDTHS_H
