/**
 * GraphSAGE Layer for FPGA Implementation - PURE INT8 VERSION (PARAMETRIC)
 *
 * - Pure integer arithmetic: NO floating-point in datapath.
 * - INT8 activations and weights.
 * - Fixed-point scales with M fractional bits.
 * - All micro-architecture knobs (unroll factors, pipeline II, resource
 *   binding, bit-widths) are configurable via macros.
 *
 * Quantization scheme (same as your previous version):
 *   - Weights:    INT8 symmetric.
 *   - Activations:INT8 symmetric.
 *   - Accumulators: INT32.
 *   - Adjacency:  scaled and stored as integer (adj_t).
 *   - Scales:     fixed-point scale_fp_t with M_BITS fractional bits.
 *
 * Key formulas:
 *   Aggregation:
 *      q_agg[i,f] = clamp( (sum_j(A_int[i,j] * q_in[j,f]) * beta_fp
 *                           + 2^(M-1)) >> M )
 *
 *   Linear:
 *      q_out[n,o] = clamp( (acc * eff_scale_fp + 2^(M-1)) >> M )
 *
 * Where:
 *   beta_fp      = round(scale_in / (K * scale_out) * 2^M)
 *   eff_scale_fp = round((scale_in * scale_w / scale_out) * 2^M)
 */

#pragma once

#include <stdint.h>
#ifndef __SYNTHESIS__
#include <cstdio>
#endif

#include <ap_int.h>

// ============================================================================
// OPTIMIZED BIT-WIDTHS SUPPORT
// ============================================================================
//
// To use auto-generated optimized bit-widths:
//   1. Run: cd src && python optimize_bitwidths_int8.py
//   2. Either define USE_OPTIMIZED_BITWIDTHS before including this header, or
//   3. Pass -DUSE_OPTIMIZED_BITWIDTHS to the compiler
//
// This will include auto_generated_bitwidths.h and use OPT_* values.
// Without this flag, conservative defaults are used.

#ifdef USE_OPTIMIZED_BITWIDTHS
#include "auto_generated_bitwidths.h"
#endif

// ============================================================================
// High-level configuration (graph / feature sizes)
// ============================================================================

#ifndef NUM_NODES
#ifdef USE_OPTIMIZED_BITWIDTHS
#define NUM_NODES OPT_NUM_NODES
#else
#define NUM_NODES 8
#endif
#endif

#ifndef IN_FEATURES
#ifdef USE_OPTIMIZED_BITWIDTHS
#define IN_FEATURES OPT_IN_FEATURES
#else
#define IN_FEATURES 16
#endif
#endif

#ifndef HIDDEN_FEATURES
#ifdef USE_OPTIMIZED_BITWIDTHS
#define HIDDEN_FEATURES OPT_HIDDEN_FEATURES
#else
#define HIDDEN_FEATURES 24
#endif
#endif

#ifndef OUT_FEATURES
#ifdef USE_OPTIMIZED_BITWIDTHS
#define OUT_FEATURES OPT_OUT_FEATURES
#else
#define OUT_FEATURES 7
#endif
#endif

// ============================================================================
// Fixed-point configuration (scales, adjacency, accumulators)
// ============================================================================

// Number of fractional bits for fixed-point scales (M in docs).
// - M=20: ~13 LSB max error vs PTQ-Float, smaller multipliers.
// - M=24: 0 LSB error (exact match), larger multipliers.
#ifndef M_BITS
#ifdef USE_OPTIMIZED_BITWIDTHS
#define M_BITS OPT_M_BITS
#else
#define M_BITS 24
#endif
#endif

// Adjacency scaling: A_float * (1 << K_BITS) -> adj_t
// Default K=2^12 = 4096 (as in your PTQ analysis).
#ifndef K_BITS
#ifdef USE_OPTIMIZED_BITWIDTHS
#define K_BITS OPT_K_BITS
#else
#define K_BITS 12
#endif
#endif

// Bit-widths for internal integer types.
// These can be tuned manually or auto-generated by optimize_bitwidths_int8.py.

#ifndef ADJ_BITS
#ifdef USE_OPTIMIZED_BITWIDTHS
// Use data-driven optimized value
#define ADJ_BITS OPT_ADJ_BITS
#else
// Adjacency values are scaled by 2^K_BITS and typically in [0,1],
// so 1 sign bit + K_BITS is plenty. Use a bit of margin.
#define ADJ_BITS (K_BITS + 4)   // e.g. 16 bits when K_BITS=12
#endif
#endif

#ifndef ACC_BITS
#ifdef USE_OPTIMIZED_BITWIDTHS
// Use data-driven optimized value (typically much smaller than 32)
#define ACC_BITS OPT_ACC_BITS
#else
// Conservative default: Accumulator for sums of muls.
#define ACC_BITS 32
#endif
#endif

#ifndef SCALE_BITS
#ifdef USE_OPTIMIZED_BITWIDTHS
// Use data-driven optimized value
#define SCALE_BITS OPT_SCALE_BITS
#else
// Fixed-point scale value: eff_scale_fp, beta_fp.
// Needs to represent +/- (something close to 2^M).
#define SCALE_BITS (M_BITS + 8)  // some headroom
#endif
#endif

#ifndef MULT_BITS
#ifdef USE_OPTIMIZED_BITWIDTHS
// Use data-driven optimized value (typically much smaller than 64)
#define MULT_BITS OPT_MULT_BITS
#else
// Product width: acc * scale_fp, tmp * beta_fp.
// Rule of thumb: ACC_BITS + SCALE_BITS - M_BITS + margin.
#define MULT_BITS (ACC_BITS + SCALE_BITS)
#endif

// Rounding constant: (1 << (M_BITS - 1)) in MULT domain
// (cast to MULT_BITS to avoid truncation).
#define ROUND_CONST ((ap_int<MULT_BITS>)(1) << (M_BITS - 1))

// ============================================================================
// Micro-architecture knobs (unroll, pipeline, binding)
// ============================================================================
//
// These let you control parallelism from the outside (via -D...).
// Default values are "safe" (no outer unrolling, II=1 inner pipelining).

// ---- Aggregation (aggregate_int8) ----

// Pipeline II for the (i,f) loop in aggregation
#ifndef AGG_PIPELINE_II
#define AGG_PIPELINE_II 1
#endif

// Unroll factor for J loop (neighbors)
#ifndef AGG_UNROLL_J
#define AGG_UNROLL_J 1
#endif

// ---- Linear (linear_int8) ----

// Pipeline II for (n,o) loop in linear
#ifndef LIN_PIPELINE_II
#define LIN_PIPELINE_II 1
#endif

// Unroll factor for F loop (features)
#ifndef LIN_UNROLL_F
#define LIN_UNROLL_F 1
#endif

// ---- ReLU (relu_int8) ----

// Unroll factor for ReLU loops
#ifndef RELU_UNROLL_F
#define RELU_UNROLL_F 1
#endif

// ---- Resource binding knobs (bind_op) ----
//
// You can enable these to push some multipliers to fabric or enforce DSP.
// By default they are disabled; you enable by defining macros in your script.
//
// Example (aggregation mul in fabric):
//   -DAGG_MUL_IN_FABRIC
//
// Example (linear scaling mul in DSP with latency 2):
//   -DLIN_SCALE_IN_DSP -DLIN_SCALE_LATENCY=2

// Aggregation: adj * feature -> tmp
// If defined, the mul will be implemented in LUT fabric.
#ifdef AGG_MUL_IN_FABRIC
#define AGG_BIND_MUL_FABRIC
#endif

// Linear scaling: acc * eff_scale_fp or tmp * beta_fp
// If defined, the mul will be implemented in DSP.
#ifdef LIN_SCALE_IN_DSP
#ifndef LIN_SCALE_LATENCY
#define LIN_SCALE_LATENCY 1
#endif
#define LIN_BIND_SCALE_DSP
#endif

// ============================================================================
// Type definitions - PURE INTEGER VERSION
// ============================================================================

// Quantized activations and weights (INT8)
typedef ap_int<8>        data_t;
typedef ap_int<8>        weight_t;

// Adjacency matrix entries (scaled by 2^K_BITS)
typedef ap_int<ADJ_BITS> adj_t;

// Accumulator (MAC sums)
typedef ap_int<ACC_BITS> acc_t;

// Bias in accumulator domain
typedef ap_int<ACC_BITS> bias_t;

// Fixed-point scale factors (eff_scale_fp, beta_fp)
typedef ap_int<SCALE_BITS> scale_fp_t;

// Intermediate product for fixed-point scaling
typedef ap_int<MULT_BITS> mult_t;

// ============================================================================
// Helper: clamp MULT_BITS to INT8 range [-128, 127]
// ============================================================================

inline data_t int8_clamp(mult_t x) {
#pragma HLS INLINE
    if (x > 127)
        return data_t(127);
    if (x < -128)
        return data_t(-128);
    return data_t(x);
}

// ============================================================================
// Helper: fixed-point multiply and shift with rounding
// result = (a * b + ROUND_CONST) >> M_BITS
// a: ACC or similar, b: scale_fp_t
// ============================================================================

inline mult_t fp_mult_shift(acc_t a, scale_fp_t b) {
#pragma HLS INLINE
    mult_t product = (mult_t)a * (mult_t)b;
    mult_t rounded = product + ROUND_CONST;
    return rounded >> M_BITS;
}

// ============================================================================
// Pure integer aggregation
// ============================================================================

/**
 * Integer-only aggregation:
 *
 *   q_agg[i,f] = clamp( ( sum_j(adj[i,j] * q_in[j,f]) * beta_fp
 *                         + 2^(M-1) ) >> M )
 *
 * - adj_matrix is integer-scaled adjacency (adj_t).
 * - features are INT8.
 * - beta_fp encodes scale_in / (K * scale_out).
 */
template<int N_NODES, int N_FEAT>
void aggregate_int8(
    const adj_t  adj_matrix[N_NODES][N_NODES],
    const data_t features[N_NODES][N_FEAT],
    data_t       agg_out[N_NODES][N_FEAT],
    scale_fp_t   beta_fp
) {
#pragma HLS INLINE

AGG_I:
    for (int i = 0; i < N_NODES; i++) {
    AGG_F:
        for (int f = 0; f < N_FEAT; f++) {
#pragma HLS PIPELINE II=AGG_PIPELINE_II

            // INT accumulator for sum_j(adj * feat)
            acc_t tmp = 0;

        AGG_J:
            for (int j = 0; j < N_NODES; j++) {
#if AGG_UNROLL_J > 1
#pragma HLS UNROLL factor=AGG_UNROLL_J
#endif
                // INT16-ish * INT8 -> ACC
                acc_t prod = (acc_t)adj_matrix[i][j] * (acc_t)features[j][f];

#ifdef AGG_BIND_MUL_FABRIC
#pragma HLS BIND_OP variable=prod op=mul impl=fabric
#endif

                tmp += prod;
            }

            // tmp is in "adj * feat" units.
            // Apply fixed-point scale beta_fp: (tmp * beta_fp + ROUND) >> M.
            mult_t scaled = (mult_t)tmp * (mult_t)beta_fp;
            mult_t rounded = scaled + ROUND_CONST;
            mult_t result = rounded >> M_BITS;

            agg_out[i][f] = int8_clamp(result);

#ifndef __SYNTHESIS__
            if (i == 6 && f < 3) {
                printf("  AGG_INT8: node=%d feat=%d tmp=%d scaled=%lld result=%lld out=%d\n",
                       i, f,
                       (int)tmp,
                       (long long)scaled,
                       (long long)result,
                       (int)agg_out[i][f]);
            }
#endif
        }
    }
}

// ============================================================================
// Pure integer linear transform
// ============================================================================

/**
 * Integer-only linear:
 *
 *   acc = bias[o] + sum_f( q_in[n,f] * w[o,f] )
 *   q_out[n,o] = clamp( (acc * eff_scale_fp + 2^(M-1)) >> M )
 *
 * - bias is pre-scaled to accumulator domain:
 *     bias_int32 = round(bias_float / (scale_in * scale_w))
 * - eff_scale_fp encodes (scale_in * scale_w / scale_out) * 2^M
 */
template<int N_NODES, int IN_FEAT, int OUT_FEAT>
void linear_int8(
    const data_t  features[N_NODES][IN_FEAT],
    const weight_t weights[OUT_FEAT][IN_FEAT],
    const bias_t   bias[OUT_FEAT],
    data_t         output[N_NODES][OUT_FEAT],
    scale_fp_t     eff_scale_fp
) {
#pragma HLS INLINE

LIN_N:
    for (int n = 0; n < N_NODES; n++) {
    LIN_O:
        for (int o = 0; o < OUT_FEAT; o++) {
#pragma HLS PIPELINE II=LIN_PIPELINE_II

            // Start with bias in accumulator domain.
            acc_t acc = bias[o];

        LIN_F:
            for (int f = 0; f < IN_FEAT; f++) {
#if LIN_UNROLL_F > 1
#pragma HLS UNROLL factor=LIN_UNROLL_F
#endif
                acc += (acc_t)features[n][f] * (acc_t)weights[o][f];
            }

            // Apply fixed-point scale: (acc * eff_scale_fp + ROUND) >> M.
            mult_t scaled = (mult_t)acc * (mult_t)eff_scale_fp;
#ifdef LIN_BIND_SCALE_DSP
#pragma HLS BIND_OP variable=scaled op=mul impl=dsp latency=LIN_SCALE_LATENCY
#endif
            mult_t rounded = scaled + ROUND_CONST;
            mult_t result = rounded >> M_BITS;

            output[n][o] = int8_clamp(result);

#ifndef __SYNTHESIS__
            if (n == 6 && o < 3) {
                printf("  LIN_INT8: node=%d out=%d acc=%d scaled=%lld result=%lld out=%d\n",
                       n, o,
                       (int)acc,
                       (long long)scaled,
                       (long long)result,
                       (int)output[n][o]);
            }
#endif
        }
    }
}

// ============================================================================
// Pure integer ReLU
// ============================================================================

/**
 * ReLU with symmetric quantization (zero_point = 0):
 *   q_out = max(0, q_in)
 */
template<int N_NODES, int N_FEAT>
void relu_int8(
    data_t data[N_NODES][N_FEAT]
) {
#pragma HLS INLINE

RELU_N:
    for (int n = 0; n < N_NODES; n++) {
    RELU_F:
        for (int f = 0; f < N_FEAT; f++) {
#if RELU_UNROLL_F > 1
#pragma HLS UNROLL factor=RELU_UNROLL_F
#endif
            if (data[n][f] < 0) {
                data[n][f] = 0;
            }
        }
    }
}

// ============================================================================
// Full network - Pure INT8
// ============================================================================

/**
 * Two-layer GraphSAGE network - PURE INT8 VERSION
 *
 * Layer 1:
 *   agg1   = aggregate_int8(input, beta1_fp)
 *   hidden = ReLU( linear_int8(agg1, W1, b1, eff_scale1_fp) )
 *
 * Layer 2:
 *   agg2   = aggregate_int8(hidden, beta2_fp)
 *   output = linear_int8(agg2, W2, b2, eff_scale2_fp)
 *
 * All operations are done in integer-only fixed-point arithmetic.
 */
template<int N_NODES, int IN_FEAT, int HIDDEN_FEAT, int OUT_FEAT>
void graphsage_int8_template(
    const adj_t   adj_matrix[N_NODES][N_NODES],
    const data_t  input[N_NODES][IN_FEAT],
    const weight_t weights1[HIDDEN_FEAT][IN_FEAT],
    const bias_t   bias1[HIDDEN_FEAT],
    const weight_t weights2[OUT_FEAT][HIDDEN_FEAT],
    const bias_t   bias2[OUT_FEAT],
    data_t         output[N_NODES][OUT_FEAT],
    scale_fp_t     beta1_fp,
    scale_fp_t     beta2_fp,
    scale_fp_t     eff_scale1_fp,
    scale_fp_t     eff_scale2_fp
) {
    // Do NOT pipeline the whole function; internal loops are pipelined.
    // This keeps control over II and resource use local to each kernel.

    // Intermediate buffers (no full partitioning by default).
    data_t agg1  [N_NODES][IN_FEAT];
    data_t hidden[N_NODES][HIDDEN_FEAT];
    data_t agg2  [N_NODES][HIDDEN_FEAT];

#ifndef __SYNTHESIS__
    printf("\n=== INT8 HLS: LAYER 1 AGGREGATION (beta1_fp=%d) ===\n",
           (int)beta1_fp);
#endif

    aggregate_int8<N_NODES, IN_FEAT>(
        adj_matrix, input, agg1, beta1_fp
    );

#ifndef __SYNTHESIS__
    printf("Agg1[6,:8] = [");
    for (int f = 0; f < 8 && f < IN_FEAT; f++) {
        printf("%d%s", (int)agg1[6][f], f < 7 ? ", " : "");
    }
    printf("]\n");
    printf("\n=== INT8 HLS: LAYER 1 LINEAR (eff_scale1_fp=%d) ===\n",
           (int)eff_scale1_fp);
#endif

    linear_int8<N_NODES, IN_FEAT, HIDDEN_FEAT>(
        agg1, weights1, bias1, hidden, eff_scale1_fp
    );
    relu_int8<N_NODES, HIDDEN_FEAT>(hidden);

#ifndef __SYNTHESIS__
    printf("Hidden[6,:8] = [");
    for (int f = 0; f < 8 && f < HIDDEN_FEAT; f++) {
        printf("%d%s", (int)hidden[6][f], f < 7 ? ", " : "");
    }
    printf("]\n");
    printf("\n=== INT8 HLS: LAYER 2 AGGREGATION (beta2_fp=%d) ===\n",
           (int)beta2_fp);
#endif

    aggregate_int8<N_NODES, HIDDEN_FEAT>(
        adj_matrix, hidden, agg2, beta2_fp
    );

#ifndef __SYNTHESIS__
    printf("Agg2[6,:8] = [");
    for (int f = 0; f < 8 && f < HIDDEN_FEAT; f++) {
        printf("%d%s", (int)agg2[6][f], f < 7 ? ", " : "");
    }
    printf("]\n");
    printf("\n=== INT8 HLS: LAYER 2 LINEAR (eff_scale2_fp=%d) ===\n",
           (int)eff_scale2_fp);
#endif

    linear_int8<N_NODES, HIDDEN_FEAT, OUT_FEAT>(
        agg2, weights2, bias2, output, eff_scale2_fp
    );

#ifndef __SYNTHESIS__
    printf("Output[6,:] = [");
    for (int f = 0; f < OUT_FEAT; f++) {
        printf("%d%s", (int)output[6][f], f < OUT_FEAT - 1 ? ", " : "");
    }
    printf("]\n");
    printf("\n=== INT8 HLS COMPLETE ===\n\n");
#endif
}

// ============================================================================
// Top-level wrapper for HLS synthesis
// ============================================================================

/**
 * Non-templated top function using default sizes from macros.
 * You can still instantiate graphsage_int8_template<> directly
 * if you want multiple configurations.
 */
void graphsage_int8(
    const adj_t   adj_matrix[NUM_NODES][NUM_NODES],
    const data_t  input    [NUM_NODES][IN_FEATURES],
    const weight_t weights1[HIDDEN_FEATURES][IN_FEATURES],
    const bias_t   bias1   [HIDDEN_FEATURES],
    const weight_t weights2[OUT_FEATURES][HIDDEN_FEATURES],
    const bias_t   bias2   [OUT_FEATURES],
    data_t         output  [NUM_NODES][OUT_FEATURES],
    scale_fp_t     beta1_fp,
    scale_fp_t     beta2_fp,
    scale_fp_t     eff_scale1_fp,
    scale_fp_t     eff_scale2_fp
);

#endif // GRAPHSAGE_LAYER_INT8_H
