universe    = vanilla
initialdir  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls
should_transfer_files = NO
getenv = True
request_cpus   = 2
request_memory = 8G
request_disk   = 2G
log    = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/tps_B5_thrscan.$(Cluster).$(Process).log
output = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/tps_B5_thrscan.$(Cluster).$(Process).out
error  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/tps_B5_thrscan.$(Cluster).$(Process).err

executable = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/scripts/omtf_gmt/run_threshold_scan_tps_h64.sh
queue
