universe    = vanilla
initialdir  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls
executable  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/pipeline/append_g9g10.sh
should_transfer_files = NO
getenv = True
request_cpus   = 4
request_memory = 16G
request_disk   = 8G
log    = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/tps_v3_dataset.$(Cluster).$(Process).log
output = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/tps_v3_dataset.$(Cluster).$(Process).out
error  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/tps_v3_dataset.$(Cluster).$(Process).err
queue
