universe    = vanilla
initialdir  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls
executable  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/pipeline/validate.sh
arguments   = $(dataset)

should_transfer_files = NO
getenv = True

request_cpus   = 2
request_memory = 8G
request_disk   = 2G

log    = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/validate_g_full.$(Cluster).$(Process).log
output = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/validate_g_full.$(Cluster).$(Process).out
error  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/validate_g_full.$(Cluster).$(Process).err

queue dataset in (G1 G2 G3 G4 G5 G6 G7 G8)
