universe    = vanilla
initialdir  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls
should_transfer_files = NO
getenv = True
request_cpus   = 4
request_memory = 16G
request_disk   = 8G
log    = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/internal_cache_build.$(Cluster).$(Process).log
output = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/internal_cache_build.$(Cluster).$(Process).out
error  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/internal_cache_build.$(Cluster).$(Process).err

executable = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/scripts/omtf/run_build_internal_cache.sh
queue
