universe = vanilla

initialdir = /lhome/ext/uovi156/uovi1562/gnn_dse_hls
executable = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/scripts/omtf/run_omtf_train.sh

should_transfer_files = NO
getenv = True

request_cpus = 4
request_memory = 20G
request_disk = 8G
request_gpus = 1

log    = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/omtf_train.$(Cluster).$(Process).log
output = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/omtf_train.$(Cluster).$(Process).out
error  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/omtf_train.$(Cluster).$(Process).err

arguments = edge_compat S1+S2+S3+S5+B1+B2+B3+B4 50 128 0 0 build/omtf/cache/schema_v1_graph

queue
