universe    = vanilla
initialdir  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls
should_transfer_files = NO
getenv = True
request_cpus   = 4
request_memory = 24G
request_disk   = 4G
request_gpus   = 1
+UseNvidiaA100 = True
log    = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/internal_train.$(Cluster).$(Process).log
output = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/internal_train.$(Cluster).$(Process).out
error  = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/build/condor/internal_train.$(Cluster).$(Process).err

executable = /lhome/ext/uovi156/uovi1562/gnn_dse_hls/scripts/omtf/run_train_eval_internal_h64_hn025.sh
queue
